### ISSUE TITLE
[Question] Any ways to save the project with a script?

### ISSUE THREAD

**Issue by leostudiooo** [Dreamtonics/svstudio-scripts#13]
Hi, 

I'm working on an auto-save script and I wonder if there is a method to save the project with a script. But I couldn't find anything related to this in *the manual*.
Or if there is an open API for the read-and-write function so that I can write into a project file manually?

**Comment by linyuansup** [comment]
And in my opinion, the auto save is very important. All in all, I don't want to lose my 1-hour-edited file because of the crash of sv once again.
Of course, add the auto save function in sv is also very useful. But I think an open API support could give the turner or coder more way to expand the function of sv.
